apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest-deployment
spec:
  selector:
    matchLabels:
      app: rest-server
  template:
    metadata:
      labels:
        app: rest-server
    spec:
      containers:
      - name: rest-server
        image: lilanga/go-grpc-rest-microservice-http:v0.3
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rest-service
spec:
  selector:
    app: rest-server
  ports:
  - port: 8080
    nodePort: 30080
  type: NodePort

